version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./react
      dockerfile: ../dockerfiles/frontend.dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./react/src:/app/src
      - /app/node_modules
    # environment:
    #   - VITE_API_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./express
      dockerfile: ../dockerfiles/backend.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./express:/app
      - /app/node_modules
    # environment:
    #   - NODE_ENV=development
    # command: npm start
